zeromq/zeromq.org

- config.toml
Hotlink should be okay according to https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia
> Add hotlink to mongrel2 icon on wikipedia

- content/docs/api.md
Solution: Remove the old link from Getting started section
> Problem: Content has link to Low-level API twice

- assets/sass/style.sass
Solution: Center the icon on the navbar for tablet and mobile
> Problem: ZeroMQ icon on the left for tablet and mobile feels wrong

- content/languages/c.md
- content/languages/cplusplus.md
- content/languages/csharp.md
- content/languages/erlang.md
- content/languages/fsharp.md
- content/languages/go.md
- content/languages/haskell.md
- content/languages/java.md
- content/languages/nodejs.md
- content/languages/perl.md
- content/languages/python.md
- content/languages/ruby.md
- content/languages/rust.md
Solution: Remove the markdown headers because headers are set through
the title attribute in the frontmatter
> Problem: Duplicate title for language pages

- content/docs/examples/c/czmq/hello_world_client.md
- content/docs/examples/c/czmq/hello_world_server.md
- content/docs/examples/c/czmq/pubsub_topics_pub.md
- content/docs/examples/c/czmq/pubsub_topics_sub.md
- content/docs/examples/c/libzmq/hello_world_client.md
- content/docs/examples/c/libzmq/hello_world_server.md
- content/docs/examples/c/libzmq/pubsub_topics_pub.md
- content/docs/examples/c/libzmq/pubsub_topics_sub.md
- content/docs/socket_api.md
Solution: Use scattered information from libzmq docs, NetMQ docs and the
zguide to wrap up a introduction into the socket api.
This page has examples for libzmq and czmq. Examples for other
languages and bindings can be easily added as well ;)
> Draft: ZeroMQ socket api -> examples czmq and libzmq

- layouts/partials/content.html
Solution: Ensure they stay on the same row by adding the is-mobile
class
> Problem: Language/Lib select boxes are broken into two rows

- content/languages/nodejs.md
The examples as they currently are, are not working. The simple fix is to use the compatibility layer. The correct fix would be to use v6 syntax, but since it's still in beta, I'd say updating the examples so they work is higher priority
> Update to use compatability layer

- content/languages/nodejs.md
The current latest version of `zeromq` ([6.0.0-beta.6](https://www.npmjs.com/package/zeromq/v/6.0.0-beta.6) by the time of writing) [has no support](https://github.com/zeromq/zeromq.js/blob/v6.0.0-beta.6/src/compat.ts#L423-L436) for `bindSync`. To make the documentation working, we may ask users to use versio 5 branch for now.
> nodejs: Use zeromq@5 branch

- content/languages/nodejs.md
This PR adds changes which should have been included in #61.
> nodejs: Use zeromq since we have fixed to zeromq@5

- content/docs/examples/cpp/zmqpp/index.md
Solution: Make examples headless by adding an index.md
> Problem: zmqpp examples are shown in sidebar

- content/docs/examples/rust/rust-zmq/hello_world_client.md
- content/docs/examples/rust/rust-zmq/hello_world_server.md
Solution: copy the examples from [rust-zmq repository](https://github.com/erickt/rust-zmq/tree/master/examples/zguide).
> Problem: no "Hello world" example for Rust

- content/docs/examples/rust/rust-zmq/index.md
> Problem: rust-zmq/index.md is missing

- layouts/shortcodes/example.html
Solution: add the code for creating `index.md` to example contributor's instructions.
> Problem: contributors forget to add index.md

- layouts/partials/footer.html
Solution: Add a link in the footer, that this site is powered by Netlify
> Problem: zeromq.org doesn't refer to our free hosting service

- content/languages/csharp.md
According to this (https://github.com/zeromq/netmq/issues/827), curve encryption has been added in 4.0.1.4, hope docs can be added for how to implement curves!
> Update NetMQ with curves

- config.toml
It seems the addition of "page:all" at the end of these URLs causes 404 where if you remove that they work properly.
Maybe some mis-typed hugo magic?
> Fix "The Guide" links which are 404

- README.md
- content/docs/examples/python/pyzmq/hello_world_client.md
- content/docs/examples/python/pyzmq/hello_world_server.md
- fixed typos
- word wrap
- grammatical errors
Use f-strings instead of the % operator, which shouldn't be encouraged in writing new code. Using the `.format` method would also work here since its addition in Python `3.x`, but f-strings have been supported since `3.6` and the default in all new distros is already `3.8` at this point.
> docs: Readme and Python Examples updates

- content/languages/c.md
It's better to have links on page to follow the link and not need to copy and open another tab.
> Update c.md fix links on page

- content/languages/python.md
There was a misplaced bracket causing the link to PyPi to be placed on top of the table rather than within it.
> Fix link to PyPi

- content/docs/examples/c/libzmq/pubsub_topics_pub.md
"status" contains 6 characters, not 5
> Fixed length issue in example

- config.toml
Hi ZeroMQ team. earlier, I made a mistake because of the naming of the logos we have. This time, I've fixed that.
> fix: jina.ai logo on website again.

- content/languages/cplusplus.md
Without this change, the rendered page on https://zeromq.org/languages/cplusplus/ shows only plaintext URLs, that cannot be clicked.
The github preview is misleading, because the hyperlink is clickable even without <a href=""></a>
> cplusplus: add explicit hyperlinks to the projects

- content/docs/examples/cpp/cppzmq/pubsub_topics_pub.md
This makes the PUB consistent with its SUB and with the C examples
> Send multipart of pairs instead of pairs of single parts.

- content/languages/csharp.md
If you see https://zeromq.org/languages/csharp/, you'll notice that the links I've changed aren't actually anchor links. My change corrects that (and sets the target to _blank.
> Change links to actually work

- Makefile
- content/docs/how-to-contribute.md
Problem:
* all libzmq documentation pages are pointing to the "contribution policy page" http://zeromq.wikidot.com/docs:contributing which lands on the "old" zeromq website; this can be misleading for newcomers, given that the old zeromq website is full of outdated references and information. 
Solution:
* Just migrate the content from old "as is" from the old wiki to the new website
> Migrate "how to contribute" page from old wiki

- content/docs/how-to-contribute.md
Problem: how-to-contribute page has no good formatting and outdated contents
Solution: 
update links to working ones;
remove git documentation that is now better served by Github (also explains how to fork the project);
embed the Coding Style page of the old wikisite in this how-to-contribute page to avoid adding yet another item in the left-menu of the website; make it clear the coding style applies only to libzmq and czmq and that now clang-format is in use.
> Fix "How to contribute" formatting and review its contents

- content/languages/rust.md
Crate installation example and crate links were inconsistent from last update - fixed. Added alternative crate from zeromq project itself
> Languages - rust. Fix crate installation and add alternative

- content/docs/examples/cpp/cppzmq/raddsh_dish_example.md
- content/docs/examples/cpp/cppzmq/raddsh_radio_example.md
- content/docs/socket_api.md
I noticed that the [Socket API docs](https://zeromq.org/socket-api/#radio-dish-pattern) for Radio-Dish list the message group as limited to 16 bytes, whereas the [RFC](https://rfc.zeromq.org/spec/48/#group) and [implementation](https://github.com/zeromq/libzmq/blob/481cc3fa2c4414e407d863b4428f1efd5441e97d/include/zmq.h#L368) allow up to 255. While I was fixing that, I thought I'd throw in some radio-dish examples too.
> Fix up radio dish socket docs

- content/docs/get-started.md
This reverts commit 1b8914000b693d00b6f4b7e5a4982dded8fc5526.
The commit added an exact copy of the [libzmq example](https://github.com/zeromq/zeromq.org/blob/7e5c182a9f05177798a71687d4e15d3267ef85de/content/docs/examples/c/libzmq/hello_world_client.md) to the get started page, such that it is displayed for all languages with improper markup.
> Fix get started page

- data/libraries.yaml
Somewhat confusingly, the name of the [git repo](https://gitlab.com/twittner/zeromq-haskell) is "zeromq-haskell" but the actual Haskell package is called "zeromq4-haskell". Corrected name in site to "zeromq4-haskell".
> Corrected name of haskell lib - zeromq4-haskell
