content/languages/nodejs.md

This PR adds installation instructions for NodeJS and brings over some examples from the official package README.

problem: no content for nodejs language

---

assets/sass/style.sass
layouts/partials/javascript.html
static/js/copy-code-button.js

Solution: Add a copy button to all code blocks
This solution is copied from:
https://www.dannyguo.com/blog/how-to-add-copy-to-clipboard-buttons-to-code-blocks-in-hugo/

Problem: To copy a code block text need to be manually marked

---

assets/sass/style.sass
config.toml
content/docs/examples/c/czmq/index.md
content/docs/examples/c/czmq/messages_func.md
content/docs/examples/c/czmq/messages_strings_send_recv.md
content/docs/examples/c/czmq/messages_strings_send_recv_multi.md
content/docs/examples/c/libzmq/index.md
content/docs/examples/c/libzmq/messages_func.md
content/docs/examples/c/libzmq/messages_strings_send_recv.md
content/docs/examples/c/libzmq/messages_strings_send_recv_multi.md
content/docs/messages.md
layouts/partials/content.html
layouts/partials/javascript.html
layouts/shortcodes/example.html
static/js/language-switch.js

Solution: Start by explaining the ZeroMQ messages and because ZeroMQ has
so many bindings and different implementations make the examples
selectable by using two select boxes: language and library.
@Info: The changes are in draft state and as such are only visible if
hugo is build in draft mode. None of the changes will influence the
appearance of the current live docs.

Problem: Website is missing gentle introduction into ZeroMQ

---

content/docs/examples/c/czmq/messages_func.md
content/docs/examples/c/libzmq/messages_strings_send_recv_multi.md
content/docs/messages.md

Solution: Conclude the sections

Problem: Messages strings chapter is incomplete for libzmq and czmq

---

assets/js/app.js
assets/sass/style.sass
layouts/partials/content.html
layouts/partials/navbar.html

Solution: Move the TOC on mobile and tablet into a separate menu
that can be displayed by clicking the TOC button on the top left.

Problem: On mobile we need to scroll the TOC until content is visible

---

assets/sass/style.sass
layouts/index.html
layouts/partials/content.html
layouts/partials/header.html
static/js/language-switch.js

* Smaller hero and footer to allow for more content space
* Drop the description from the hero as IMO it is not useful to the reader
* Smaller menu on large screens
* Fixes to the language/library example selection (only draft mode currently)

Hero and Footer improvements

---

assets/sass/style.sass
layouts/partials/content.html

Solution: Add an edit page button to the top right of the content

Problem: Its not obvious to potential contributors how to edit a page

---

content/docs/socket_api.md

Solution: Aggregate information from the libzmq docs and the RFC

Problem: Request-reply pattern section is missing details

---

README.md
archetypes/examples/hello_world_client.md
archetypes/examples/hello_world_server.md
archetypes/examples/index.md
archetypes/examples/messages_strings_send_recv.md
archetypes/examples/messages_strings_send_recv_multi.md
archetypes/examples/pubsub_topics_pub.md
archetypes/examples/pubsub_topics_sub.md

Solution: Create an hugo archtype which will create stubs for each
example and add a description to the README on how to use it.

Problem: It is not documented how to add/translate examples for new langauges/libraries

---

netlify.toml

Solution: Update to the most recent release

Problem: Netlify hugo build version lacks behind 6 months

---

content/docs/socket_api.md
layouts/shortcodes/note.html

Solution: Make them complete :)

Problem: Client/Server and Radio/Dish pattern section incomplete

---

assets/sass/style.sass
layouts/partials/content.html

Solution: Add a label inside the select box as a hint

Problem: select boxes for language and library are not self explaining

---

content/docs/get-started.md

Solution: Copy the text from NetMQ docs which seems to be copied from
the zguide ;)

Problem: Zero in ZeroMQ not explained

---

assets/sass/style.sass
layouts/partials/content.html

Solution: Reduce the max-width[1] of the content to increase readability
but still be wide enough for code snippets to show completely.
[1] https://baymard.com/blog/line-length-readability

Problem: When reading website on desktop its hard to focus on text

---

content/docs/community.md

Problem: event page location out of date

---

content/docs/examples/c/czmq/messages_strings_send_recv_multi.md
content/docs/examples/csharp/netmq/messages_strings_send_recv_multi.md
content/docs/socket_api.md

Problem: Found typos

---

content/docs/socket_api.md

Solution: Remove it from socket api

Problem: First example is already used in getting started

---

content/docs/examples/cpp/zmqpp/hello_world_client.md
content/docs/examples/cpp/zmqpp/hello_world_server.md

I look example in [zmqpp](https://github.com/zeromq/zmqpp/tree/develop/examples) repo and implement basic hello world example.

cpp: add zmqpp hello world example

---

content/docs/examples/c/libzmq/hello_world_server.md

Solution: add assert.h include in server code

Problem: cannot compile libzmq helloworld server

---

content/docs/examples/cpp/cppzmq/hello_world_client.md
content/docs/examples/cpp/cppzmq/hello_world_server.md
content/docs/examples/cpp/cppzmq/index.md

Problem: hello world examples missing for cppzmq C++ language binding

---

data/libraries.yaml
layouts/shortcodes/libraries.html

Solution: Remove unnecessary labels or replace with icons

Problem: library cards are verbose

---

content/docs/examples/c/libzmq/hello_world_server.md
content/docs/examples/cpp/zmqpp/hello_world_server.md

Problem: minor typo in hello_world c/cpp examples

---

content/docs/examples/cpp/zmqpp/download.md
content/docs/examples/erlang/chumak/download.md
fetch_examples.sh

Solution: Fetch installation from latest git README

Problem: Missing install and download for zmqpp and chumack

---

netlify.toml

Solution: Set the attribute force = true so the current behaviour is not
effected by that change.

Problem: Netlify implied force for redirect changes on 07-04-2020

---

content/docs/examples/cpp/cppzmq/hello_world_client.md
content/docs/examples/cpp/cppzmq/hello_world_server.md

Problem: Example for cppzmq can be modernized

---

content/docs/examples/erlang/chumak/hello_world_client.md
content/docs/examples/erlang/chumak/hello_world_server.md

- `hello_world_server.md`
- `hello_world_client.md`
for erlang chumak

erlang: chumak examples

---

content/languages/python.md

- this should be done on all pages

added hyperlinks to the links on top

---

config.toml

Preview:
Jina project:
http://github.com/jina-ai/jina
@somdoron Thanks for the call today, looking forward to the next level of collab.

add Jina to "used by"

---

content/docs/examples/python/pyzmq/hello_world_client.md
content/docs/examples/python/pyzmq/hello_world_server.md

The examples were not showed here : https://zeromq.org/get-started/?language=python&library=pyzmq#
I just added the code as shown here : http://zguide.zeromq.org/py:chapter1

Add hello_world example for pyzmq

---

content/docs/examples/go/zmq4/hello_world_client.md
content/docs/examples/go/zmq4/hello_world_server.md

Added hello_world examples to Golang zmq4

---

content/languages/go.md

Typo fixes in go.md

---

content/docs/examples/c/libzmq/download.md

Solution: remove them
Fixes https://github.com/zeromq/zeromq.org/issues/113

Problem: dead links for Windows pre-built binaries

---

content/community/community.md

Solution: move to libera.chat as other projects are doing

Problem: freenode has been taken over

---

config.toml

Fix #121 Jina.ai logo URL

---

content/languages/go.md

Instruction was spelt instrunction

Fixed spelling mistake in go.md

---

content/languages/c.md
content/languages/fsharp.md

Quick Typo patch fix
It stood out when I was reading docs.

Quick Typo patch fix

---

content/docs/examples/cpp/cppzmq/pubsub_topics_pub.md
content/docs/examples/cpp/cppzmq/pubsub_topics_sub.md

1. add examples/cpp/cppzmq/pubsub_topics_sub.md
2. add examples/cpp/cppzmq/pubsub_topics_pub.md

add pubsub example of cppzmq

---

content/docs/examples/haskell/zeromq4-haskell/hello_world_client.md
content/docs/examples/haskell/zeromq4-haskell/hello_world_server.md
content/docs/examples/haskell/zeromq4-haskell/index.md

Implemented *Hello World* client and server in Haskell
**PS:** The other language examples had auto-generated `download.md` files. I didn't include `download.md` in Haskell example directory as I wasn't sure where to make changes so that it would be auto-generated.

Haskell: Hello World client and server

---

content/languages/zig.md
data/libraries.yaml

Hi, added the Zig binding. Please feel free to modify any changes. Best Regards, Felix

Add Zig binding

---

content/docs/examples/zig/zzmq/download.md
content/docs/examples/zig/zzmq/hello_world_client.md
content/docs/examples/zig/zzmq/hello_world_server.md
content/docs/examples/zig/zzmq/index.md
fetch_examples.sh

Add missing example files. Best Regards, Felix

Add Zig binding II

---

content/languages/nodejs.md

Fixes https://github.com/zeromq/zeromq.js/issues/645

docs: update Zeromq.js docs for v6

---

content/docs/examples/go/goczmq/hello_world_client.md
content/docs/examples/go/goczmq/hello_world_server.md

Solution: Refer to [goczmq repository](https://github.com/zeromq/goczmq).

Problem: hello world examples missing for Go goczmq
